name: CMake CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Build Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential libboost-all-dev libasio-dev

    - name: Install Crow Framework
      run: |
        git clone https://github.com/CrowCpp/Crow.git
        cd Crow
        mkdir build && cd build
        cmake .. -DCROW_BUILD_EXAMPLES=OFF -DCROW_BUILD_TESTS=OFF
        sudo make install

    - name: Install Vulkan
      run: sudo apt-get install -y vulkan-tools libvulkan-dev vulkan-validationlayers-dev spirv-tools glslc

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DS2_VULKAN=ON
    
    - name: Build Project
      run: cmake --build build --parallel $(nproc)
