name: Windows CMake CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Crow Framework
      shell: bash
      run: |
        git clone https://github.com
        cd Crow
        mkdir build && cd build
        cmake .. -DCROW_BUILD_EXAMPLES=OFF -DCROW_BUILD_TESTS=OFF
        cmake --build . --target install --config Release

    - name: Configure CMake (Windows + Vulkan)
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DS2_VULKAN=ON
    
    - name: Build Project
      run: cmake --build build --config Release --parallel

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: 2s-Windows11-Vulkan
        path: build/Release/2s.exe
